apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ml-model-pdb
  namespace: production
spec:
  selector:
    matchLabels:
      app: ml-model
  minAvailable: 2  # Always keep at least 2 pods running