apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-model-metrics
  namespace: production
  labels:
    app: ml-model
spec:
  selector:
    matchLabels:
      app: ml-model
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s